# Generated by Django 4.1.6 on 2023-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.PositiveIntegerField(choices=[('USD', 'usd'), ('EUR', 'eur')]),
        ),
    ]
