# Generated by Django 4.1.6 on 2023-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'usd'), (2, 'eur')]),
        ),
    ]
